### ISSUE TITLE
Chat-related architecture

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Architecture#7]
AS AN Architect
I WANT TO have chat-related architecture defined
SO THAT all related developments would be based on these requirements

### Acceptance Criteria

- [ ] Provide applicable Mermaid diagrams for specific use-case
- [ ] All use cases must have business-level diagrams without (excess) technical details
- [ ] All business-level diagrams must be linked to applicable technical diagrams
- [ ] All technical diagrams must be linked to applicable repositories
- [ ] All technical diagrams must be linked to applicable deployment scripts
- [ ] All technical diagrams must be linked to applicable automated tests

#### Documentation

- [ ] All chat-related architectural documentation must reside in https://github.com/buerokratt/Architecture/tree/main/docs/chat

#### Scope

- [ ] buerokratt/Architecture#6
